# version: "3.8"

services:
  authentik-worker:
    image: ghcr.io/goauthentik/server:2024.10.1
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
    profiles: [security]
    entrypoint: ["/entrypoint-wrapper.sh"]
    command: ["dumb-init", "--", "ak", "worker"]

