# version: "3.8"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      cap_add:
        - ALL
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
    profiles: [monitoring]
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.${DOMAIN}`)"
      - "traefik.http.routers.cadvisor.entrypoints=websecure"
      - "traefik.http.routers.cadvisor-web.entrypoints=web"
      - "traefik.http.routers.cadvisor-web.rule=Host(`cadvisor.${DOMAIN}`)"
      - "traefik.http.routers.cadvisor.tls.certresolver=cloudflare"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
      - "homepage.group=Monitoring"
      - "homepage.name=cAdvisor"
      - "homepage.icon=docker.png"
      - "homepage.href=https://cadvisor.${DOMAIN}"
      - "homepage.description=Container resource monitoring"
