use_default_settings: true
general:
  debug: false
  instance_name: "SearXNG"
search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "en"
server:
  secret_key: "6d442253cc32d8d4bb8849c627871d5c4bf702883d29b9571980802c22e4c10b"
  limiter: false
  image_proxy: true
ui:
  static_use_hash: true
