# version: "3.8"

services:
  guacamole:
    image: guacamole/guacamole:latest
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
    profiles: [productivity]

