version: "3.8"

services:
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: unless-stopped
    profiles: [productivity]
    volumes:
      - guacd_drive:/drive:rw
      - guacd_record:/record:rw
    networks:
      - ai-ml

networks:
  ai-ml:
    external: true

volumes:
  guacd_drive:
    external: true
  guacd_record:
    external: true
