# version: "3.8"

services:
  guacd:
    image: guacamole/guacd:latest
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
    profiles: [productivity]
    volumes:
      - guacd_drive:/drive:rw
      - guacd_record:/record:rw
    networks:
      - proxy
      - ai-ml


