# version: "3.8"

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    profiles: [ai]
    environment:
#      OLLAMA_BASE_URL: http://ollama:11434
#      WEBUI_SECRET_KEY_FILE: /run/secrets/webui_secret_key
# Use host-gateway to exit the Open WebUI container and hit your laptop's port 8642
      OPENAI_API_BASE_URL: "http://host.docker.internal:8642/v1"
      OPENAI_API_KEY: "your-super-secret-key-here" # Must match the key from Step 1!
      ENABLE_OLLAMA_API: "false"
    ports:
      - "127.0.0.1:${PORT_OPENWEBUI}:8080"
    volumes:
      - ./data:/app/backend/data
    secrets:
      - webui_secret_key
    networks:
      - proxy
      - ai-ml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`chat.${DOMAIN}`)"
      - "traefik.http.routers.openwebui.entrypoints=websecure"
      - "traefik.http.routers.openwebui-web.entrypoints=web"
      - "traefik.http.routers.openwebui-web.rule=Host(`chat.${DOMAIN}`)"
      - "traefik.http.routers.openwebui.tls.certresolver=cloudflare"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
      - "homepage.group=AI"
      - "homepage.name=OpenWebUI"
      - "homepage.href=https://chat.${DOMAIN}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  proxy:
    external: true
  ai-ml:
    external: true
